### Hezhong Skywars 配置文件
### 一个新的单端空岛战争插件
### 作者 tjshawa

# 权限节点：
# 命令：hsw.command

basicInfo:
  # 基本信息配置
  serverIp: "&eHezhong Technology" # 显示用的服务器地址，可填写字符串，解析颜色代码
  serverName: "&e&lExample" # 显示用，服务器名称，解析颜色代码
  lobbyWorld: "world" # 大厅世界

  defaultGameMode: "adventure" # 大厅的默认游戏模式，可选survival/daventure/spectator/creative
bungee:
  bungee: true # 启用跨服？
  proxyType: "bc" # bc即BungeeCord，vc即Velocity
  serverType: "lobby" # lobby即大厅服务器，game即游戏服务器
  serverName: "lobby1" # BungeeCord中你服务器名称，必须准确
redis: # 启用跨服则需要配置Redis，以进行通信
  host: "127.0.0.1"
  port: 6379
  password: ""
  ssl: false # Redis SSL
  channel: "hsw:csm"
database:
  type: "sqlite" # sqlite / mysql
  
  # SQLite 配置（type 为 sqlite 时生效）
  sqlite:
    file: "plugins/HezhongSkywars/data.db" # 数据库文件路径（相对于服务端根目录）
    table-prefix: "hezhongsw" # 数据表前缀
    
  # MySQL 配置（type 为 mysql 时生效）
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "114514"
    database: "skywars"
    table-prefix: "hezhongsw"
    reconnect-timeout: 5000 # 重连超时，毫秒

coins:
  winAdd: 100 # 一局胜利游戏能获得的硬币
  killAdd: 10 # 击杀一个玩家能获得的硬币

exp:
  winAdd: 100 # 一局胜利游戏能获得的经验
  killAdd: 10 # 一局胜利游戏能获得的经验

levels:
  # 游戏内等级
  #
  # 达到指定的经验后，可达到对应等级
  needExps: [0, 1000, 3000, 5000, 8000, 12000, 15000] # 达到该等级需要的经验，一项一级。不满第一级则是第一级。

multiWorld:
  independentChat: true # 独立每个世界的聊天
  independentTab: true # 独立每个世界的TAB列表




